//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.31 at 10:29:41 AM IST 
//


package com.londonhydro.datamigration.domain;

import javax.persistence.*;
import javax.xml.bind.annotation.*;


/**
 * [extension] Customer action notification (e.g., delinquency, move in, move out)
 * 
 * <p>Java class for AccountNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountNotification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://naesb.org/espi/customer}Object"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="methodKind" type="{http://naesb.org/espi/customer}NotificationMethodKind"/&gt;
 *         &lt;element name="time" type="{http://naesb.org/espi/customer}TimeType"/&gt;
 *         &lt;element name="note" type="{http://naesb.org/espi/customer}String256"/&gt;
 *         &lt;element name="customerNotificationKind" type="{http://naesb.org/espi/customer}String256"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountNotification", propOrder = {
    "methodKind",
    "time",
    "note",
    "customerNotificationKind"
})
@Entity
@Table(name="account_notification")
public class AccountNotification
    extends Object
{
    @XmlTransient
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    @XmlElement(required = true)
    @Column(name="method_kind")
    protected String methodKind;

    @Column(name="time")
    protected long time;

    @XmlElement(required = true)
    @Column(name="note")
    protected String note;

    @XmlElement(required = true)
    @Column(name="customer_notification_kind")
    protected String customerNotificationKind;

    @XmlTransient
    @ManyToOne
    @JoinColumn(name="customer_account_id")
    protected CustomerAccount customerAccountId;

    /**
     * Gets the value of the methodKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodKind() {
        return methodKind;
    }

    /**
     * Sets the value of the methodKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodKind(String value) {
        this.methodKind = value;
    }

    /**
     * Gets the value of the time property.
     * 
     */
    public long getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     */
    public void setTime(long value) {
        this.time = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the customerNotificationKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNotificationKind() {
        return customerNotificationKind;
    }

    /**
     * Sets the value of the customerNotificationKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNotificationKind(String value) {
        this.customerNotificationKind = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CustomerAccount getCustomerAccountId() {
        return customerAccountId;
    }

    public void setCustomerAccountId(CustomerAccount customerAccountId) {
        this.customerAccountId = customerAccountId;
    }
}
